version: '3'
services:
  
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:3000"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres
  #   restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hospital_management
      POSTGRES_USER: Venki
      POSTGRES_PASSWORD: Venki@034
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/l9_iot_platform.sql:/docker-entrypoint-initdb.d/l9_iot_platform.sql
        # docker-compose exec postgres pg_restore -U Life9 -d l9_iot_platform /docker-entrypoint-initdb.d/l9_iot_platform.sql
    restart: always



volumes:
  postgres_data:
